#!/bin/bash
# check-lockfiles.sh - Verify lockfile presence and integrity

set -e

PROJECT_PATH="${1:-.}"

if [ ! -d "$PROJECT_PATH" ]; then
    echo "Error: Project path '$PROJECT_PATH' not found"
    exit 1
fi

check_npm() {
    local project="$1"
    local has_package_json=false
    local has_lockfile=false
    local lockfile_type=""

    if [ -f "$project/package.json" ]; then
        has_package_json=true
    fi

    if [ -f "$project/package-lock.json" ]; then
        has_lockfile=true
        lockfile_type="package-lock.json"
    elif [ -f "$project/yarn.lock" ]; then
        has_lockfile=true
        lockfile_type="yarn.lock"
    elif [ -f "$project/pnpm-lock.yaml" ]; then
        has_lockfile=true
        lockfile_type="pnpm-lock.yaml"
    fi

    if [ "$has_package_json" = true ]; then
        echo "npm: package.json found"
        if [ "$has_lockfile" = true ]; then
            echo "  OK: Lockfile found ($lockfile_type)"
            return 0
        else
            echo "  WARN: No lockfile detected (need: package-lock.json, yarn.lock, or pnpm-lock.yaml)"
            return 1
        fi
    fi
}

check_python() {
    local project="$1"
    local has_requirements=false
    local has_lockfile=false
    local lockfile_type=""

    if [ -f "$project/requirements.txt" ] || [ -f "$project/pyproject.toml" ] || [ -f "$project/Pipfile" ]; then
        has_requirements=true
    fi

    if [ -f "$project/poetry.lock" ]; then
        has_lockfile=true
        lockfile_type="poetry.lock"
    elif [ -f "$project/Pipfile.lock" ]; then
        has_lockfile=true
        lockfile_type="Pipfile.lock"
    elif [ -f "$project/requirements.lock" ]; then
        has_lockfile=true
        lockfile_type="requirements.lock"
    fi

    if [ "$has_requirements" = true ]; then
        echo "Python: requirements/pyproject.toml found"
        if [ "$has_lockfile" = true ]; then
            echo "  OK: Lockfile found ($lockfile_type)"
            return 0
        else
            echo "  WARN: No lockfile detected (need: poetry.lock, Pipfile.lock, or requirements.lock)"
            return 1
        fi
    fi
}

check_rust() {
    local project="$1"
    local has_toml=false
    local has_lockfile=false

    if [ -f "$project/Cargo.toml" ]; then
        has_toml=true
    fi

    if [ -f "$project/Cargo.lock" ]; then
        has_lockfile=true
    fi

    if [ "$has_toml" = true ]; then
        echo "Rust: Cargo.toml found"
        if [ "$has_lockfile" = true ]; then
            echo "  OK: Cargo.lock found"
            return 0
        else
            echo "  WARN: Cargo.lock not found (required for reproducible builds)"
            return 1
        fi
    fi
}

check_go() {
    local project="$1"
    local has_mod=false
    local has_sum=false

    if [ -f "$project/go.mod" ]; then
        has_mod=true
    fi

    if [ -f "$project/go.sum" ]; then
        has_sum=true
    fi

    if [ "$has_mod" = true ]; then
        echo "Go: go.mod found"
        if [ "$has_sum" = true ]; then
            echo "  OK: go.sum found"
            return 0
        else
            echo "  WARN: go.sum not found (required for dependency verification)"
            return 1
        fi
    fi
}

check_java() {
    local project="$1"

    if [ -f "$project/pom.xml" ]; then
        echo "Java/Maven: pom.xml found"
        if [ -f "$project/pom.xml.lock" ] || [ -f "$project/.mvn/maven.config" ]; then
            echo "  OK: Lock mechanism configured"
            return 0
        else
            echo "  WARN: No explicit dependency lock (consider maven-lockfile-maven-plugin)"
            return 1
        fi
    fi

    if [ -f "$project/build.gradle" ] || [ -f "$project/build.gradle.kts" ]; then
        echo "Java/Gradle: build.gradle found"
        echo "  WARN: Gradle dependency locking not enabled (use dependencyLocking)"
        return 1
    fi
}

verify_lockfile_integrity() {
    local project="$1"

    echo ""
    echo "Integrity Checks:"
    echo "================="

    if [ -f "$project/package-lock.json" ] && [ -f "$project/package.json" ]; then
        # Check if lockfile was generated by npm
        if ! grep -q '"lockfileVersion"' "$project/package-lock.json"; then
            echo "  ERROR: package-lock.json may be corrupted (missing lockfileVersion)"
        else
            echo "  OK: package-lock.json structure valid"
        fi
    fi

    if [ -f "$project/yarn.lock" ] && [ -f "$project/package.json" ]; then
        if ! head -1 "$project/yarn.lock" | grep -q "yarn lockfile"; then
            echo "  WARN: yarn.lock header missing"
        else
            echo "  OK: yarn.lock structure valid"
        fi
    fi

    if [ -f "$project/go.sum" ] && [ -f "$project/go.mod" ]; then
        local sum_lines=$(wc -l < "$project/go.sum")
        if [ "$sum_lines" -lt 1 ]; then
            echo "  WARN: go.sum is empty"
        else
            echo "  OK: go.sum contains $sum_lines entries"
        fi
    fi
}

main() {
    echo "Supply Chain Security Auditor - Lockfile Verification"
    echo "====================================================="
    echo ""

    local has_issues=0

    check_npm "$PROJECT_PATH" || has_issues=$((has_issues + 1))
    check_python "$PROJECT_PATH" || has_issues=$((has_issues + 1))
    check_rust "$PROJECT_PATH" || has_issues=$((has_issues + 1))
    check_go "$PROJECT_PATH" || has_issues=$((has_issues + 1))
    check_java "$PROJECT_PATH" || has_issues=$((has_issues + 1))

    verify_lockfile_integrity "$PROJECT_PATH"

    echo ""
    echo "Summary:"
    echo "========"
    if [ $has_issues -eq 0 ]; then
        echo "OK: All detected projects have lockfiles"
        exit 0
    else
        echo "WARNING: $has_issues package manager(s) missing lockfiles"
        echo "Impact: Non-deterministic builds, supply chain vulnerability"
        exit 1
    fi
}

main "$@"
